events {
    worker_connections 1024;
}

# Minecraft bruger TCP ikke HTTP, så vi bruger stream modulet til at proxye trafikken
stream {
    # Opretter en tabel ved navn minecraft der tracker samtidige forbindelser og har 10MB hukkomelse allokeret
    limit_conn_zone $remote_addr zone=minecraft:10m;

    server {
        listen 25565;                        # Lyt mod internettet
        proxy_pass minecraft_minecraft:25565;   # Videresend internt
        proxy_timeout 600s; # Maks tid til at forbinde til mc server
        proxy_connect_timeout 10s; # maks tid uden aktivitet før connection lukkes


        limit_conn minecraft 5; # Maks 5 samtidige forbindelser pr ip
    }
}
